# Copyright (c) 2017, The MITRE Corporation. All rights reserved.
# See LICENSE.txt for complete terms.

# This is an auto-generated file.
# maec	-	4.1.0.13

__date__ = "2017-04-20 15:01:04.342000"


# Maps Python instance attribute names to XML instance field names for
# Python API classes.
_FIELDS = {
    "maec.bundle.action_reference_list.ActionReferenceList": {
        "action_reference": "Action_Reference",
    },
    "maec.bundle.av_classification.AVClassification": {
        "description": "Description",
        "id_": "@id",
        "idref": "@idref",
        "name": "Name",
        "service_pack": "Service_Pack",
        "tool_hashes": "Tool_Hashes",
        "type_": "Type",
        "vendor": "Vendor",
        "version": "Version",
    },
    "maec.bundle.av_classification.AVClassifications": {
        "av_classification": "AV_Classification",
    },
    "maec.bundle.behavior.AssociatedCode": {
        "code_snippet": "Code_Snippet",
    },
    "maec.bundle.behavior.Behavior": {
        "action_composition": "Action_Composition",
        "associated_code": "Associated_Code",
        "description": "Description",
        "discovery_method": "Discovery_Method",
        "duration": "@duration",
        "id_": "@id",
        "ordinal_position": "@ordinal_position",
        "purpose": "Purpose",
        "status": "@status",
    },
    "maec.bundle.behavior.BehaviorPurpose": {
        "description": "Description",
        "vulnerability_exploit": "Vulnerability_Exploit",
    },
    "maec.bundle.behavior.BehavioralAction": {
        "behavioral_ordering": "@behavioral_ordering",
    },
    "maec.bundle.behavior.BehavioralActionEquivalenceReference": {
        "action_equivalence_idref": "@action_equivalence_idref",
        "behavioral_ordering": "@behavioral_ordering",
    },
    "maec.bundle.behavior.BehavioralActionReference": {
        "action_id": "@action_id",
        "behavioral_ordering": "@behavioral_ordering",
    },
    "maec.bundle.behavior.BehavioralActions": {
        "action": "Action",
        "action_collection": "Action_Collection",
        "action_equivalence_reference": "Action_Equivalence_Reference",
        "action_reference": "Action_Reference",
    },
    "maec.bundle.behavior.CVEVulnerability": {
        "cve_id": "@cve_id",
        "description": "Description",
    },
    "maec.bundle.behavior.Exploit": {
        "cve": "CVE",
        "cwe_id": "CWE_ID",
        "known_vulnerability": "@known_vulnerability",
        "targeted_platforms": "Targeted_Platforms",
    },
    "maec.bundle.behavior.PlatformList": {
        "platform": "Platform",
    },
    "maec.bundle.behavior_reference.BehaviorReference": {
        "behavior_idref": "@behavior_idref",
    },
    "maec.bundle.bundle.ActionCollection": {
        "action_list": "Action_List",
        "affinity_degree": "Affinity_Degree",
        "affinity_type": "Affinity_Type",
        "description": "Description",
        "id_": "@id",
        "name": "@name",
    },
    "maec.bundle.bundle.ActionCollectionList": {
        "action_collection": "Action_Collection",
    },
    "maec.bundle.bundle.ActionList": {
        "action": "Action",
    },
    "maec.bundle.bundle.BaseCollection": {
        "affinity_degree": "Affinity_Degree",
        "affinity_type": "Affinity_Type",
        "description": "Description",
        "name": "@name",
    },
    "maec.bundle.bundle.BehaviorCollection": {
        "affinity_degree": "Affinity_Degree",
        "affinity_type": "Affinity_Type",
        "behavior_list": "Behavior_List",
        "description": "Description",
        "id_": "@id",
        "name": "@name",
    },
    "maec.bundle.bundle.BehaviorCollectionList": {
        "behavior_collection": "Behavior_Collection",
    },
    "maec.bundle.bundle.BehaviorList": {
        "behavior": "Behavior",
    },
    "maec.bundle.bundle.BehaviorReference": {
        "behavior_idref": "@behavior_idref",
    },
    "maec.bundle.bundle.Bundle": {
        "actions": "Actions",
        "av_classifications": "AV_Classifications",
        "behaviors": "Behaviors",
        "candidate_indicators": "Candidate_Indicators",
        "capabilities": "Capabilities",
        "collections": "Collections",
        "content_type": "@content_type",
        "defined_subject": "@defined_subject",
        "id_": "@id",
        "malware_instance_object_attributes": "Malware_Instance_Object_Attributes",
        "objects": "Objects",
        "process_tree": "Process_Tree",
        "schema_version": "@schema_version",
        "timestamp": "@timestamp",
    },
    "maec.bundle.bundle.CandidateIndicatorCollection": {
        "affinity_degree": "Affinity_Degree",
        "affinity_type": "Affinity_Type",
        "candidate_indicator_list": "Candidate_Indicator_List",
        "description": "Description",
        "id_": "@id",
        "name": "@name",
    },
    "maec.bundle.bundle.CandidateIndicatorCollectionList": {
        "candidate_indicator_collection": "Candidate_Indicator_Collection",
    },
    "maec.bundle.bundle.Collections": {
        "action_collections": "Action_Collections",
        "behavior_collections": "Behavior_Collections",
        "candidate_indicator_collections": "Candidate_Indicator_Collections",
        "object_collections": "Object_Collections",
    },
    "maec.bundle.bundle.ObjectCollection": {
        "affinity_degree": "Affinity_Degree",
        "affinity_type": "Affinity_Type",
        "description": "Description",
        "id_": "@id",
        "name": "@name",
        "object_list": "Object_List",
    },
    "maec.bundle.bundle.ObjectCollectionList": {
        "object_collection": "Object_Collection",
    },
    "maec.bundle.bundle.ObjectList": {
        "object": "Object",
    },
    "maec.bundle.bundle_reference.BundleReference": {
        "bundle_idref": "@bundle_idref",
    },
    "maec.bundle.candidate_indicator.CandidateIndicator": {
        "author": "Author",
        "composition": "Composition",
        "creation_datetime": "@creation_datetime",
        "description": "Description",
        "id_": "@id",
        "importance": "Importance",
        "lastupdate_datetime": "@lastupdate_datetime",
        "malware_entity": "Malware_Entity",
        "numeric_importance": "Numeric_Importance",
        "version": "@version",
    },
    "maec.bundle.candidate_indicator.CandidateIndicatorComposition": {
        "action_reference": "Action_Reference",
        "behavior_reference": "Behavior_Reference",
        "object_reference": "Object_Reference",
        "operator": "@operator",
        "sub_composition": "Sub_Composition",
    },
    "maec.bundle.candidate_indicator.CandidateIndicatorList": {
        "candidate_indicator": "Candidate_Indicator",
    },
    "maec.bundle.candidate_indicator.MalwareEntity": {
        "description": "Description",
        "name": "Name",
        "type_": "Type",
    },
    "maec.bundle.capability.Capability": {
        "behavior_reference": "Behavior_Reference",
        "description": "Description",
        "id_": "@id",
        "name": "@name",
        "property": "Property",
        "relationship": "Relationship",
        "strategic_objective": "Strategic_Objective",
        "tactical_objective": "Tactical_Objective",
    },
    "maec.bundle.capability.CapabilityList": {
        "capability": "Capability",
        "capability_reference": "Capability_Reference",
    },
    "maec.bundle.capability.CapabilityObjective": {
        "behavior_reference": "Behavior_Reference",
        "description": "Description",
        "id_": "@id",
        "name": "Name",
        "property": "Property",
        "relationship": "Relationship",
    },
    "maec.bundle.capability.CapabilityObjectiveReference": {
        "objective_idref": "@objective_idref",
    },
    "maec.bundle.capability.CapabilityObjectiveRelationship": {
        "objective_reference": "Objective_Reference",
        "relationship_type": "Relationship_Type",
    },
    "maec.bundle.capability.CapabilityProperty": {
        "name": "Name",
        "value": "Value",
    },
    "maec.bundle.capability.CapabilityReference": {
        "capability_idref": "@capability_idref",
    },
    "maec.bundle.capability.CapabilityRelationship": {
        "capability_reference": "Capability_Reference",
        "relationship_type": "Relationship_Type",
    },
    "maec.bundle.malware_action.APICall": {
        "address": "Address",
        "function_name": "@function_name",
        "normalized_function_name": "@normalized_function_name",
        "parameters": "Parameters",
        "return_value": "Return_Value",
    },
    "maec.bundle.malware_action.ActionImplementation": {
        "api_call": "API_Call",
        "code": "Code",
        "id_": "@id",
        "type_": "@type",
    },
    "maec.bundle.malware_action.MalwareAction": {
        "action_aliases": "Action_Aliases",
        "action_arguments": "Action_Arguments",
        "action_status": "@action_status",
        "associated_objects": "Associated_Objects",
        "context": "@context",
        "description": "Description",
        "discovery_method": "Discovery_Method",
        "frequency": "Frequency",
        "id_": "@id",
        "idref": "@idref",
        "implementation": "Implementation",
        "name": "Name",
        "ordinal_position": "@ordinal_position",
        "relationships": "Relationships",
        "timestamp": "@timestamp",
        "type_": "Type",
    },
    "maec.bundle.malware_action.Parameter": {
        "name": "@name",
        "ordinal_position": "@ordinal_position",
        "value": "@value",
    },
    "maec.bundle.malware_action.ParameterList": {
        "parameter": "Parameter",
    },
    "maec.bundle.object_reference.ObjectReferenceList": {
        "object_reference": "Object_Reference",
    },
    "maec.bundle.process_tree.ProcessTree": {
        "root_process": "Root_Process",
    },
    "maec.bundle.process_tree.ProcessTreeNode": {
        "argument_list": "Argument_List",
        "child_pid_list": "Child_PID_List",
        "creation_time": "Creation_Time",
        "custom_properties": "Custom_Properties",
        "environment_variable_list": "Environment_Variable_List",
        "extracted_features": "Extracted_Features",
        "id_": "@id",
        "image_info": "Image_Info",
        "initiated_actions": "Initiated_Actions",
        "injected_process": "Injected_Process",
        "is_hidden": "@is_hidden",
        "kernel_time": "Kernel_Time",
        "name": "Name",
        "network_connection_list": "Network_Connection_List",
        "object_reference": "@object_reference",
        "ordinal_position": "@ordinal_position",
        "parent_action_idref": "@parent_action_idref",
        "parent_pid": "Parent_PID",
        "pid": "PID",
        "port_list": "Port_List",
        "spawned_process": "Spawned_Process",
        "start_time": "Start_Time",
        "user_time": "User_Time",
        "username": "Username",
    },
    "maec.package.action_equivalence.ActionEquivalence": {
        "action_reference": "Action_Reference",
        "id_": "@id",
    },
    "maec.package.action_equivalence.ActionEquivalenceList": {
        "action_equivalence": "Action_Equivalence",
    },
    "maec.package.analysis.Analysis": {
        "analysis_environment": "Analysis_Environment",
        "analysts": "Analysts",
        "comments": "Comments",
        "complete_datetime": "@complete_datetime",
        "dynamic_analysis_metadata": "Dynamic_Analysis_Metadata",
        "findings_bundle_reference": "Findings_Bundle_Reference",
        "id_": "@id",
        "lastupdate_datetime": "@lastupdate_datetime",
        "method": "@method",
        "ordinal_position": "@ordinal_position",
        "report": "Report",
        "source": "Source",
        "start_datetime": "@start_datetime",
        "summary": "Summary",
        "tools": "Tools",
        "type_": "@type",
    },
    "maec.package.analysis.AnalysisEnvironment": {
        "analysis_systems": "Analysis_Systems",
        "hypervisor_host_system": "Hypervisor_Host_System",
        "network_infrastructure": "Network_Infrastructure",
    },
    "maec.package.analysis.AnalysisSystem": {
        "available_physical_memory": "Available_Physical_Memory",
        "bios_info": "BIOS_Info",
        "custom_properties": "Custom_Properties",
        "date": "Date",
        "hostname": "Hostname",
        "installed_programs": "Installed_Programs",
        "local_time": "Local_Time",
        "network_interface_list": "Network_Interface_List",
        "object_reference": "@object_reference",
        "os": "OS",
        "processor": "Processor",
        "system_time": "System_Time",
        "timezone_dst": "Timezone_DST",
        "timezone_standard": "Timezone_Standard",
        "total_physical_memory": "Total_Physical_Memory",
        "uptime": "Uptime",
        "username": "Username",
    },
    "maec.package.analysis.AnalysisSystemList": {
        "analysis_system": "Analysis_System",
    },
    "maec.package.analysis.CapturedProtocol": {
        "interaction_level": "@interaction_level",
        "layer4_protocol": "@layer4_protocol",
        "layer7_protocol": "@layer7_protocol",
        "port_number": "@port_number",
    },
    "maec.package.analysis.CapturedProtocolList": {
        "protocol": "Protocol",
    },
    "maec.package.analysis.Comment": {
        "author": "@author",
        "observation_name": "@observation_name",
        "structuring_format": "@structuring_format",
        "timestamp": "@timestamp",
        "value": "text()",
    },
    "maec.package.analysis.CommentList": {
        "comment": "Comment",
    },
    "maec.package.analysis.DynamicAnalysisMetadata": {
        "analysis_duration": "Analysis_Duration",
        "command_line": "Command_Line",
        "exit_code": "Exit_Code",
    },
    "maec.package.analysis.HypervisorHostSystem": {
        "available_physical_memory": "Available_Physical_Memory",
        "bios_info": "BIOS_Info",
        "custom_properties": "Custom_Properties",
        "date": "Date",
        "hostname": "Hostname",
        "local_time": "Local_Time",
        "network_interface_list": "Network_Interface_List",
        "object_reference": "@object_reference",
        "os": "OS",
        "processor": "Processor",
        "system_time": "System_Time",
        "timezone_dst": "Timezone_DST",
        "timezone_standard": "Timezone_Standard",
        "total_physical_memory": "Total_Physical_Memory",
        "uptime": "Uptime",
        "username": "Username",
        "vm_hypervisor": "VM_Hypervisor",
    },
    "maec.package.analysis.InstalledPrograms": {
        "program": "Program",
    },
    "maec.package.analysis.NetworkInfrastructure": {
        "captured_protocols": "Captured_Protocols",
    },
    "maec.package.analysis.Source": {
        "method": "Method",
        "name": "Name",
        "organization": "Organization",
        "reference": "Reference",
        "url": "URL",
    },
    "maec.package.analysis.ToolList": {
        "tool": "Tool",
    },
    "maec.package.grouping_relationship.ClusterComposition": {
        "edge_node_pair": "Edge_Node_Pair",
        "score_type": "@score_type",
    },
    "maec.package.grouping_relationship.ClusterEdgeNodePair": {
        "malware_subject_node_a": "Malware_Subject_Node_A",
        "malware_subject_node_b": "Malware_Subject_Node_B",
        "similarity_distance": "@similarity_distance",
        "similarity_index": "@similarity_index",
    },
    "maec.package.grouping_relationship.ClusteringAlgorithmParameters": {
        "distance_threashold": "Distance_Threashold",
        "number_of_iterations": "Number_of_Iterations",
    },
    "maec.package.grouping_relationship.ClusteringMetadata": {
        "algorithm_name": "Algorithm_Name",
        "algorithm_parameters": "Algorithm_Parameters",
        "algorithm_version": "Algorithm_Version",
        "cluster_composition": "Cluster_Composition",
        "cluster_description": "Cluster_Description",
        "cluster_size": "Cluster_Size",
    },
    "maec.package.grouping_relationship.GroupingRelationship": {
        "clustering_metadata": "Clustering_Metadata",
        "malware_family_name": "Malware_Family_Name",
        "malware_toolkit_name": "Malware_Toolkit_Name",
        "type_": "Type",
    },
    "maec.package.grouping_relationship.GroupingRelationshipList": {
        "grouping_relationship": "Grouping_Relationship",
    },
    "maec.package.malware_subject.Analyses": {
        "analysis": "Analysis",
    },
    "maec.package.malware_subject.FindingsBundleList": {
        "bundle": "Bundle",
        "bundle_external_reference": "Bundle_External_Reference",
        "meta_analysis": "Meta_Analysis",
    },
    "maec.package.malware_subject.MalwareBinaryConfigurationStorageDetails": {
        "file_offset": "File_Offset",
        "section_name": "Section_Name",
        "section_offset": "Section_Offset",
    },
    "maec.package.malware_subject.MalwareConfigurationDetails": {
        "configuration_parameter": "Configuration_Parameter",
        "obfuscation": "Obfuscation",
        "storage": "Storage",
    },
    "maec.package.malware_subject.MalwareConfigurationObfuscationAlgorithm": {
        "algorithm_name": "Algorithm_Name",
        "key": "Key",
        "ordinal_position": "@ordinal_position",
    },
    "maec.package.malware_subject.MalwareConfigurationObfuscationDetails": {
        "algorithm_details": "Algorithm_Details",
        "is_encoded": "@is_encoded",
        "is_encrypted": "@is_encrypted",
    },
    "maec.package.malware_subject.MalwareConfigurationParameter": {
        "name": "Name",
        "value": "Value",
    },
    "maec.package.malware_subject.MalwareConfigurationStorageDetails": {
        "file": "File",
        "malware_binary": "Malware_Binary",
        "url": "URL",
    },
    "maec.package.malware_subject.MalwareDevelopmentEnvironment": {
        "debugging_file": "Debugging_File",
        "tools": "Tools",
    },
    "maec.package.malware_subject.MalwareSubject": {
        "analyses": "Analyses",
        "compatible_platform": "Compatible_Platform",
        "configuration_details": "Configuration_Details",
        "development_environment": "Development_Environment",
        "findings_bundles": "Findings_Bundles",
        "id_": "@id",
        "label": "Label",
        "malware_instance_object_attributes": "Malware_Instance_Object_Attributes",
        "minor_variants": "Minor_Variants",
        "relationships": "Relationships",
    },
    "maec.package.malware_subject.MalwareSubjectList": {
        "malware_subject": "Malware_Subject",
    },
    "maec.package.malware_subject.MalwareSubjectRelationship": {
        "malware_subject_reference": "Malware_Subject_Reference",
        "type_": "Type",
    },
    "maec.package.malware_subject.MalwareSubjectRelationshipList": {
        "relationship": "Relationship",
    },
    "maec.package.malware_subject.MetaAnalysis": {
        "action_equivalences": "Action_Equivalences",
        "object_equivalences": "Object_Equivalences",
    },
    "maec.package.malware_subject.MinorVariants": {
        "minor_variant": "Minor_Variant",
    },
    "maec.package.malware_subject_reference.MalwareSubjectReference": {
        "malware_subject_idref": "@malware_subject_idref",
    },
    "maec.package.object_equivalence.ObjectEquivalence": {
        "id_": "@id",
        "object_reference": "Object_Reference",
    },
    "maec.package.object_equivalence.ObjectEquivalenceList": {
        "object_equivalence": "Object_Equivalence",
    },
    "maec.package.package.Package": {
        "grouping_relationships": "Grouping_Relationships",
        "id_": "@id",
        "malware_subjects": "Malware_Subjects",
        "schema_version": "@schema_version",
        "timestamp": "@timestamp",
    },
    "maec.vocabs.vocabs.ActionObjectAssociationType": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiBehavioralAnalysisProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiBehavioralAnalysisStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiBehavioralAnalysisTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiCodeAnalysisStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiCodeAnalysisTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiDetectionStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiDetectionTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiRemovalStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AntiRemovalTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AvailabilityViolationProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AvailabilityViolationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.AvailabilityViolationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.CapabilityObjectiveRelationship": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.CommandandControlProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.CommandandControlStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.CommandandControlTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.CommonCapabilityProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DNSActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DataExfiltrationProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DataExfiltrationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DataExfiltrationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DataTheftProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DataTheftStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DataTheftTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DebuggingActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DestructionProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DestructionStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DestructionTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DeviceDriverActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DirectoryActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.DiskActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.FTPActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.FileActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.FraudStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.FraudTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.GUIActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.GroupingRelationship": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.HTTPActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.HookingActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.IPCActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.IRCActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ImportanceType": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.InfectionPropagationProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.InfectionPropagationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.InfectionPropagationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.IntegrityViolationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.IntegrityViolationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.LibraryActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MachineAccessControlProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MachineAccessControlStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MachineAccessControlTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MalwareCapability": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MalwareConfigurationParameter": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MalwareDevelopmentTool": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MalwareEntityType": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MalwareLabel": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.MalwareSubjectRelationship": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.NetworkActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.NetworkShareActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.PersistenceProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.PersistenceStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.PersistenceTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.PrivilegeEscalationProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.PrivilegeEscalationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.PrivilegeEscalationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ProbingStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ProbingTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ProcessActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ProcessMemoryActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ProcessThreadActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.RegistryActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.RemoteMachineManipulationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.RemoteMachineManipulationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SecondaryOperationProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SecondaryOperationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SecondaryOperationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SecurityDegradationProperties": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SecurityDegradationStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SecurityDegradationTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.ServiceActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SocketActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SpyingStrategicObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SpyingTacticalObjectives": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SynchronizationActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.SystemActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
    "maec.vocabs.vocabs.UserActionName": {
        "apply_condition": "@apply_condition",
        "bit_mask": "@bit_mask",
        "condition": "@condition",
        "delimiter": "@delimiter",
        "has_changed": "@has_changed",
        "is_case_sensitive": "@is_case_sensitive",
        "pattern_type": "@pattern_type",
        "regex_syntax": "@regex_syntax",
        "trend": "@trend",
        "value": "text()",
        "vocab_name": "@vocab_name",
        "vocab_reference": "@vocab_reference",
    },
}
